### ISSUE TITLE
macOS image clock is off

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/osx-images#4]
I'm able to correct it like this:

```
  set_clock_script:
    - sudo sntp -sS pool.ntp.org
    - date # to print out the date and verify
```

Before adding this step, I was finding the clock to be off by well over an hour for the timezone it was set to.  this messed up some JWT logic I was trying to enable.  This might be as intended (if someone else on that machine changes the date manually), but just trying to verify.

**Comment by fkorotkov** [comment]
Should be fixed now. Could you please try again

**Comment by fkorotkov** [comment]
It was an unrelated to VM issue.

**Comment by dnfield** [comment]
It seems to be working, but I'm not sure if that's because I added that script to my .cirrus.yml or not.  

Do you think that is safe to remove now?  Could some other user end up changing the clock on me?

**Comment by fkorotkov** [comment]
@dnfield it's safe since I simply added `sudo sntp -sS time.apple.com` to the startup script. 😅Even though the VM has time auto syncing enabled, seems time sometimes drifts after VM gets from the suspended state into running. Anka VMs unlike Docker containers store memory snapshot as well as FS snapshot for quicker startup time.

**Comment by dnfield** [comment]
Thanks for the quick fix!
